apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: nameko-example-orders
        image: nameko/nameko-example-orders:latest
        env:
          - name: DB_HOST
            value: db-postgresql
          - name: DB_NAME
            value: orders
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-postgresql
                key: postgres-password
          - name: RABBIT_HOST
            value: broker-rabbitmq
          - name: RABBIT_MANAGEMENT_PORT
            value: "15672"
          - name: RABBIT_PORT
            value: "5672"
          - name: RABBIT_USER
            value: user
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: broker-rabbitmq
                key: rabbitmq-password
      restartPolicy: Always
